import java.util.*;

public class Main
{
    private static final String[] reverse =
    {
        "",
        "1 x 1",
        "1 x 2\n2 x 1",
        "1 x 3\n3 x 1",
        "1 x 4\n2 x 2\n4 x 1",
        "1 x 5\n5 x 1",
        "1 x 6\n2 x 3\n3 x 2\n6 x 1",
        "1 x 7\n7 x 1",
        "1 x 8\n2 x 4\n4 x 2\n8 x 1",
        "1 x 9\n3 x 3\n9 x 1",
        "2 x 5\n5 x 2",
        "",
        "2 x 6\n3 x 4\n4 x 3\n6 x 2",
        "",
        "2 x 7\n7 x 2",
        "3 x 5\n5 x 3",
        "2 x 8\n4 x 4\n8 x 2",
        "",
        "2 x 9\n3 x 6\n6 x 3\n9 x 2",
        "",
        "4 x 5\n5 x 4",
        "3 x 7\n7 x 3",
        "",
        "",
        "3 x 8\n4 x 6\n6 x 4\n8 x 3",
        "5 x 5",
        "",
        "3 x 9\n9 x 3",
        "4 x 7\n7 x 4",
        "",
        "5 x 6\n6 x 5",
        "",
        "4 x 8\n8 x 4",
        "",
        "",
        "5 x 7\n7 x 5",
        "4 x 9\n6 x 6\n9 x 4",
        "",
        "",
        "",
        "5 x 8\n8 x 5",
        "",
        "6 x 7\n7 x 6",
        "",
        "",
        "5 x 9\n9 x 5",
        "",
        "",
        "6 x 8\n8 x 6",
        "7 x 7",
        "",
        "",
        "",
        "",
        "6 x 9\n9 x 6",
        "",
        "7 x 8\n8 x 7",
        "",
        "",
        "",
        "",
        "",
        "",
        "7 x 9\n9 x 7",
        "8 x 8",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "8 x 9\n9 x 8",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "9 x 9"
    };

    public static void main(String[] args)
    {
        Scanner sc = new Scanner(System.in);
        System.out.println(reverse[2025 - sc.nextInt()]);
    }
}
